// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4Tmn8QhhBL8CSVYMlYjxlqVkSSeNl-U',
    appId: '1:369859180116:web:419ce894e1fea1620adfc1',
    messagingSenderId: '369859180116',
    projectId: 'fluttertutom2',
    authDomain: 'fluttertutom2.firebaseapp.com',
    storageBucket: 'fluttertutom2.firebasestorage.app',
    measurementId: 'G-PRYD8C8X92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjfM9I-0itgX9toqX8T88-Z96W1oO9WQ',
    appId: '1:369859180116:android:89dcdb0ad033b6130adfc1',
    messagingSenderId: '369859180116',
    projectId: 'fluttertutom2',
    storageBucket: 'fluttertutom2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7x6BN_sSl4hrXxHrgeOBAUEFGByJRqEE',
    appId: '1:369859180116:ios:c7a2aba8f918b6d10adfc1',
    messagingSenderId: '369859180116',
    projectId: 'fluttertutom2',
    storageBucket: 'fluttertutom2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7x6BN_sSl4hrXxHrgeOBAUEFGByJRqEE',
    appId: '1:369859180116:ios:c7a2aba8f918b6d10adfc1',
    messagingSenderId: '369859180116',
    projectId: 'fluttertutom2',
    storageBucket: 'fluttertutom2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF4Tmn8QhhBL8CSVYMlYjxlqVkSSeNl-U',
    appId: '1:369859180116:web:fabf7d2bd2044e750adfc1',
    messagingSenderId: '369859180116',
    projectId: 'fluttertutom2',
    authDomain: 'fluttertutom2.firebaseapp.com',
    storageBucket: 'fluttertutom2.firebasestorage.app',
    measurementId: 'G-P1M27W5Q87',
  );
}
